# Generated by Django 4.2.7 on 2023-12-07 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_assignment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class_test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ct_id', models.IntegerField()),
                ('course_code', models.CharField(max_length=50)),
                ('exam_year', models.CharField(max_length=50)),
                ('question', models.FileField(null=True, upload_to='cts/questions/')),
                ('compliance_form', models.FileField(null=True, upload_to='cts/compliance_forms/')),
                ('best_answersheet', models.FileField(null=True, upload_to='cts/best_answersheets/')),
                ('average_answersheet', models.FileField(null=True, upload_to='cts/average_answersheets/')),
                ('worst_answersheet', models.FileField(null=True, upload_to='cts/worst_answersheets/')),
            ],
        ),
        migrations.AlterField(
            model_name='assignment',
            name='compliance_form',
            field=models.FileField(null=True, upload_to='assignments/compliance_forms/'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='title',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
