# Generated by Django 4.0.3 on 2023-11-28 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicCalendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_year', models.CharField(max_length=150)),
                ('pdf_file', models.FileField(upload_to='uploads/pdfs/')),
            ],
        ),
    ]
