# Generated by Django 4.0.3 on 2023-12-27 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academicCalendar', '0002_alter_academiccalendar_pdf_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='academiccalendar',
            old_name='exam_year',
            new_name='time_span',
        ),
    ]
