# Generated by Django 4.0.3 on 2023-12-27 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academicCalendar', '0004_rename_time_span_academiccalendar_exam_year'),
    ]

    operations = [
        migrations.RenameField(
            model_name='academiccalendar',
            old_name='exam_year',
            new_name='time_span',
        ),
    ]
