# Generated by Django 4.0.3 on 2023-12-27 20:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academicCalendar', '0005_rename_exam_year_academiccalendar_time_span'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academiccalendar',
            name='time_span',
            field=models.CharField(max_length=150, unique=True, validators=[django.core.validators.RegexValidator(message="Time span must be in the format 'XXXX-XXXX' (Starting year - Ending year).", regex='^\\d{4}-\\d{4}$')]),
        ),
    ]
