# Generated by Django 4.0.3 on 2023-12-29 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_teacher'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='user_id',
            new_name='email',
        ),
    ]
