# Generated by Django 4.0.3 on 2023-12-29 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_rename_user_id_teacher_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='email',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='teacher',
            name='no_of_active_course',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='no_of_assigned_course',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='no_of_due_course_file_submission',
            field=models.IntegerField(default=0),
        ),
    ]
