# Generated by Django 4.0.3 on 2023-12-31 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_rename_email_teacher_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='no_of_active_course',
        ),
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.CharField(choices=[('Computer Science and Engineering', 'Computer Science and Engineering'), ('Physics', 'Physics'), ('Chemistry', 'Chemistry'), ('Statistics', 'Statistics'), ('Mathematics', 'Mathematics'), ('English', 'English'), ('Exam Control Office', 'Exam Control Office')], max_length=200),
        ),
        migrations.AlterField(
            model_name='user',
            name='designation',
            field=models.CharField(choices=[('Employee', 'Employee'), ('Lecturer', 'Lecturer'), ('Assistant Professor', 'Assistant Professor'), ('Associate Professor', 'Associate Professor'), ('Professor', 'Professor')], max_length=200),
        ),
    ]
