# Generated by Django 4.2.7 on 2023-12-05 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agn_id', models.IntegerField()),
                ('course_code', models.CharField(max_length=50)),
                ('exam_year', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=50)),
                ('compliance_form', models.FileField(upload_to='assignments/compliance_forms/')),
            ],
        ),
    ]
