# Generated by Django 4.2.7 on 2023-12-07 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_class_test_alter_assignment_compliance_form_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Final_exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.CharField(max_length=50)),
                ('exam_year', models.CharField(max_length=50)),
                ('question', models.FileField(null=True, upload_to='cts/questions/')),
                ('compliance_form', models.FileField(null=True, upload_to='cts/compliance_forms/')),
                ('best_answersheet', models.FileField(null=True, upload_to='cts/best_answersheets/')),
                ('average_answersheet', models.FileField(null=True, upload_to='cts/average_answersheets/')),
                ('worst_answersheet', models.FileField(null=True, upload_to='cts/worst_answersheets/')),
            ],
        ),
    ]
