# Generated by Django 4.0.3 on 2023-12-07 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_final_exam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='final_exam',
            name='average_answersheet',
            field=models.FileField(null=True, upload_to='final_exams/average_answersheets/'),
        ),
        migrations.AlterField(
            model_name='final_exam',
            name='best_answersheet',
            field=models.FileField(null=True, upload_to='final_exams/best_answersheets/'),
        ),
        migrations.AlterField(
            model_name='final_exam',
            name='compliance_form',
            field=models.FileField(null=True, upload_to='final_exams/compliance_forms/'),
        ),
        migrations.AlterField(
            model_name='final_exam',
            name='question',
            field=models.FileField(null=True, upload_to='final_exams/questions/'),
        ),
        migrations.AlterField(
            model_name='final_exam',
            name='worst_answersheet',
            field=models.FileField(null=True, upload_to='final_exams/worst_answersheets/'),
        ),
    ]
